export const CITY_ADD = 'CITY_ADD';
export const CITY_REMOVE = 'CITY_REMOVE';
export const CITY_STATUS = 'CITY_STATUS';

export const WEATHER_REQUEST = 'WEATHER_REQUEST';
export const WEATHER_RECEIVE = 'WEATHER_RECEIVE';

export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const SEARCH_RECEIVE = 'SEARCH_RECEIVE';
export const SEARCH_CLEAR = 'SEARCH_CLEAR';

export const DATA_REFRESH = 'DATA_REFRESH';
