export const CITY_ADD = 'CITY_ADD';
export const CITY_REMOVE = 'CITY_REMOVE';

export const WEATHER_REQUEST = 'WEATHER_REQUEST';
export const WEATHER_RECEIVE = 'WEATHER_RECEIVE';

export const CHANGE_STATUS = 'CHANGE_STATUS';

export const LIVE_SEARCH_REQUEST = 'LIVE_SEARCH_REQUEST';
export const LIVE_SEARCH_RECEIVE = 'LIVE_SEARCH_RECEIVE';
export const LIVE_SEARCH_REMOVE = 'LIVE_SEARCH_REMOVE';

export const DATA_REFRESH = 'DATA_REFRESH';
